### ISSUE TITLE
Move list of adjectives into its own file

### ISSUE THREAD

**Issue by uwaseem** [sanijalal/random-dessert-generator#24]
Right now, the list of adjectives sits in `index.js`.
This is fine for now, but as the list grows, the file itself will become clunky.
To keep things clean and readable, it might be worth moving the list into its own file.

**Comment by lixiaoqity** [comment]
I'd like to create a new dir to store these data.

**Comment by Yasas4D** [comment]
Hi, Please assign me

**Comment by Yasas4D** [comment]
Hi, I'm able to successfully apply the changes.. Also, I suggest a new function for getRandomNumber function as your one is not working as expected. Thank you
